### ISSUE TITLE
clean up index.js, such as modularizing all the different functions.

### ISSUE THREAD

**Issue by phentnil** [phentnil/factor-calculator#19]
https://github.com/phentnil/factor-calculator/blob/d08f0802f63ae74a31c5daa70c9259c573639b86/index.js#L26-L26

**Comment by ryepup** [comment]
one option for `theForm` would be to separate the HTML building from the logic; make some variables for all the dynamic parts of the HTML, and then splice them all together in one big string at the end. [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) can span multiple lines, so we can use that to see and edit our HTML more clearly.

For example:

```js
const buildForm = (targetForm, sort) => {
  // make a bunch of variables up here
  const target = 500; // TODO: calculate based on targetForm

  // one big string at the end
  return `
<form>
  <div>
    <label for="target">Ordered dose:</label>
  </div>
  <div>
    <input type="number" name="target" id="target" value="${target}">
  <div>
  TODO: rest of the form
</form>`;
}
